version: '3'

services:
  backend:
    build:
      context: nginx
      dockerfile: Dockerfile
#    ports:
#      - "80:80"
  tor:
    depends_on:
      - backend
    links:
      - backend
    build:
      context: .
      dockerfile: Dockerfile